### PR TITLE
update manifest and packs to v12

### PR DESCRIPTION
**Pull request by ammalagonc**
- Update the Advanced Maneuvers feat to include Howl of the Wild companions.
- Added level requirement to text description for Advanced Companions (Howl of the Wild).
- Updated the manifest to bump it to V12 and version 6.0 for the PF2e system.

### CODE REVIEW

**Comment by zarmstrong** [comment]
Can you package your PR so that it can be used by people since it looks like TikaelSol doesn't have time to merge the PR.

**Comment by TikaelSol** [comment]
I'll be merging this today or tomorrow, just have to make a release for the last v11 version of the module first.

**Comment by Mikkidez** [comment]
Tikael, can you tell if you will merge this commit in the near future? It’s just that the campaign starts in the next few days, one of the players wants to create a summoner =) If you don’t have the opportunity yet, then it’s okay, we’ll just take another class.

In any case, a huge thank you to you for this incredible work, and to all the other guys who are working on the pf2e system and modules!

**Comment by TikaelSol** [comment]
The module works fine in v12 as is, this is just a manifest bump, but I'll need to make a proper release for the last v11 version. My to-do list just keep having things added to it that have high priority so this keeps getting pushed back.

**Comment by Khunkurisu** [comment]
Any update on this? It works just fine as-is like mentioned, but having it updated officially would be excellent.

**Pull request closed without merging**
